FROM python:3.6.8

RUN pip install \
    https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl \
    https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl \
    pytest

COPY . /PyTorch_BlazeFace
RUN pip install /PyTorch_BlazeFace